version: '3.6'

services:
  postgres:
    container_name: postgres_container
    image: postgis/postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SuperSecret}
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-SuperSecret}
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_LISTEN_PORT:-49152}:80'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
